# Generated by Django 5.1.2 on 2024-10-30 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp_integration', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='whatsappmessage',
            old_name='message_body',
            new_name='body',
        ),
        migrations.AddField(
            model_name='whatsappmessage',
            name='to_number',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
